version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_USER}/${DB_HOST}
      NODE_ENV: development
      PORT: ${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:latest
    restart: always
    ports:
      - '${DB_PORT}:5432'
    volumes:
       - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes: 
  data: {}